server:
  port: 8083
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: hospital-management-system
          uri: lb://hospital-management-system
          predicates:
            - Path=/api/**